# Configuracion SG-SST (Proyecto Java Puro)
app.nombre=Sistema de Gestion SST
app.version=1.0.0

# Base de datos Supabase
db.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
db.usuario=postgres.zjikrqdhefzvpfpcjkmg
db.contrasena=sst-sg#29-db
db.pool.maxSize=10
db.pool.minIdle=2

# Servidor web embebido
server.port=8080